# Portage directories

PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"

# allow users and members of the 'portage' group can access
PORTAGE_WORKDIR_MODE="0775"
