# common portage fetch command

# auth for private mirrors
NETRC_FILE="/etc/portage/.netrc"

# mirror user agent from portage's internal python fetcher
USER_AGENT="Portage (Gentoo, https://www.gentoo.org) distfile-fetch"

# "IP Type Of Service" aka DSCP
# the main ones we care about: LE (low priority) CS0 (normal priority) EF (high priority) 
IP_TOS="LE"

FETCHCOMMAND="curl --netrc-file \"${NETRC_FILE}\" --user-agent \"${USER_AGENT}\" --ip-tos \"${IP_TOS}\" --http3 --compressed --fail --retry 3 --location \${URI} -o \${DISTDIR}/\${FILE}"
RESUMECOMMAND="${FETCHCOMMAND} --continue-at -"
