# import bashrc-utils
source /usr/share/sysbits/portage/bashrc-utils.sh

# do some extra setup
function pre_pkg_setup() {
    if [[ "${MERGE_TYPE}" != binary ]]; then
        # setup environment
        brc_build_env_setup

        # print flags
        brc_build_info
    fi
}

function post_src_configure() {
    # prettify ninja output
    brc_prettify_ninja
}
