FROM docker.io/library/alpine:3.24

ENV TMLVERSION="v2026.06.3.4"

RUN apk add dotnet8-runtime curl unzip bash

RUN curl -LO https://github.com/tModLoader/tModLoader/releases/download/${TMLVERSION}/tModLoader.zip && \
    mkdir /opt/tModLoader && \
    unzip tModLoader.zip -d /opt/tModLoader && \
    rm tModLoader.zip

RUN mv /opt/tModLoader/serverconfig.txt /opt/tModLoader/serverconfig.txt.example

WORKDIR /opt/tModLoader

COPY --chmod=755 --chown=0:0 ./entry-point.sh /entry-point.sh

EXPOSE 7777/tcp

ENTRYPOINT ["/entry-point.sh"]
